DEBUG = False
RAISE_EXCEPTION = False
DISPLAY_TRACE = False

DATABASE_PATH = "/home/user/www/flask/database.db"

DEFAULT_PAGE_SIZE = 10

API_KEY_VALIDATION_THROTTLE_TIME_S = 5

SECRET_KEY = "my_secret"